[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Nepal-College-of-Information-Technology/AI-Data-Science-Workshop-2024/blob/main/Day%203%3A%20Data%20Handling%20with%20Python/Part1_Numpy.ipynb)


## Part 1: Numpy Basics


# Introduction to Numpy

**Numpy** (Numerical Python) is a powerful library in Python that provides support for large, multi-dimensional arrays and matrices. Along with that, it offers a collection of high-level mathematical functions to operate on these arrays, making it an essential tool for scientific computing and data analysis.

In the context of data analysis, especially for cities like Kathmandu, Numpy can be incredibly useful for tasks such as:

- Analyzing temperature patterns across different times of the year.
- Monitoring traffic data at various intersections to optimize traffic flow.
- Processing large datasets related to pollution levels, population density, and many more.

## Why Numpy?

Here's a table summarizing some of the key reasons why Numpy is widely used:

| **Feature**                          | **Description**                                                                                  |
|--------------------------------------|--------------------------------------------------------------------------------------------------|
| **Efficient Array Computation**      | Numpy allows fast and efficient computation on arrays, enabling large-scale data processing.    |
| **Multi-Dimensional Arrays**         | Supports multi-dimensional arrays (1D, 2D, 3D, etc.), essential for various types of data.       |
| **Broadcasting**                     | Numpy can perform operations on arrays of different shapes, automatically expanding dimensions. |
| **Integration with Other Libraries** | Numpy serves as a foundation for many other scientific libraries, making it highly versatile.    |

### 1.1.	Installation:
If you don’t have Numpy installed, you can install it using pip:

In [1]:
# !pip install numpy

### 1.2.	Importing Numpy:
Import the Numpy library in your Python script or Jupyter Notebook:

In [2]:
import numpy as np

### 1.3 Example: Analyzing Temperature Data in Kathmandu

Let's start with a simple example where we analyze temperature data for a week in Kathmandu using Numpy. This will help you understand the basics of Numpy arrays and their operations.

In [3]:
import numpy as np

# Kathmandu temperature data (in degrees Celsius) over a week
temp_data = np.array([15.5, 16.8, 18.1, 17.3, 19.2, 20.5, 21.2])

# Days of the week
days_of_week = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]

# Print table header
print(f"+{'-'*12}+{'-'*18}+")
print(f"| {'Day':<10} | {'Temperature (°C)':<16} |")
print(f"+{'-'*12}+{'-'*18}+")

# Print table rows
for day, temp in zip(days_of_week, temp_data):
    print(f"| {day:<10} | {temp:<16} |")

# Print table footer
print(f"+{'-'*12}+{'-'*18}+")

+------------+------------------+
| Day        | Temperature (°C) |
+------------+------------------+
| Sunday     | 15.5             |
| Monday     | 16.8             |
| Tuesday    | 18.1             |
| Wednesday  | 17.3             |
| Thursday   | 19.2             |
| Friday     | 20.5             |
| Saturday   | 21.2             |
+------------+------------------+



## 2. Creating Numpy Arrays

Let's start by creating Numpy arrays. Numpy arrays are similar to Python lists but with added functionality and performance. Unlike Python lists, Numpy arrays are more efficient for numerical computations and are widely used in scientific computing, data analysis, and machine learning.

### 2.1 Creating a 1D Array

In [4]:
# Creating a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)


1D Array: [1 2 3 4 5]


### Example: Traffic Count at Sankhamul Bridge

Let’s start with a simple example where we create a 1D array representing the number of vehicles counted at different times of the day (morning, noon, evening) crossing the at Sankhamul Bridge (Lalitpur-Kathmandu).

In [5]:
# Number of vehicles at a specific intersection in Kathmandu (morning, noon, evening)
vehicles_data = np.array([3200, 4000, 4500])
print("Vehicle Count at Different Times of the Day:")
print("Morning: ", vehicles_data[0])
print("Day    : ", vehicles_data[1])
print("Evening: ", vehicles_data[2])

Vehicle Count at Different Times of the Day:
Morning:  3200
Day    :  4000
Evening:  4500



### 2.2 Creating 2D and 3D Arrays

We can create 2D and 3D arrays, which are useful for working with matrices or tensors. Numpy also supports multi-dimensional arrays, which are essential for handling more complex data structures. For instance, a 2D array can represent data across multiple intersections or times.


In [6]:
# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

print("-"*25)
# Creating a 3D array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:\n", array_3d)


2D Array:
 [[1 2 3]
 [4 5 6]]
-------------------------
3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Example: Traffic Data at Multiple Intersections
Consider a scenario where traffic data is collected at two different intersections in Kathmandu Valley at three different times of the day (morning, noon, evening). We can represent this data as a 2D array:

In [7]:
# Traffic data at two intersections (intersection 1, intersection 2) across three time periods (morning, noon, evening)
traffic_data = np.array([[3200, 6300], [4000, 8800], [4500, 6400]])
print("Traffic Data at Two Intersections:")
print(traffic_data)

Traffic Data at Two Intersections:
[[3200 6300]
 [4000 8800]
 [4500 6400]]


In this 2D array:

- **Rows** represent different times of the day (morning, noon, evening).
- **Columns** represent different intersections (Intersection 1 and Intersection 2).

This format allows for easy comparison of traffic volumes across different times and locations, which is essential for effective traffic management.

### Representing in a tabular format

In [8]:
# Traffic data at two intersections (intersection 1, intersection 2) across three time periods (morning, noon, evening)
traffic_data = np.array([[3200, 6300], [4000, 8800], [4500, 6400]])

# Time periods of the day
time_periods = ["Morning", "Noon", "Evening"]

# Print table header
print(f"+{'-'*12}+{'-'*18}+{'-'*18}+")
print(f"| {'Time ':<10} | {'Intersection 1':<16} | {'Intersection 2':<16} |")
print(f"+{'-'*12}+{'-'*18}+{'-'*18}+")

# Print table rows
for time, traffic in zip(time_periods, traffic_data):
    print(f"| {time:<10} | {traffic[0]:<16} | {traffic[1]:<16} |")

# Print table footer
print(f"+{'-'*12}+{'-'*18}+{'-'*18}+")

+------------+------------------+------------------+
| Time       | Intersection 1   | Intersection 2   |
+------------+------------------+------------------+
| Morning    | 3200             | 6300             |
| Noon       | 4000             | 8800             |
| Evening    | 4500             | 6400             |
+------------+------------------+------------------+


### Creating 3D Arrays

3D arrays can be used to represent even more complex datasets. For example, suppose we want to track traffic data across multiple days at multiple intersections. A 3D array can store this data efficiently.

### Example: Traffic Data Over Multiple Days

Imagine we collect traffic data at two intersections in Kathmandu over three days. We can structure this data into a 3D array where:

- **The first dimension** represents different days.
- **The second dimension** represents different times of the day.
- **The third dimension** represents different intersections.

In [9]:
# Traffic data over three days at two intersections (intersection 1, intersection 2)
traffic_data_3d = np.array([[[120, 130], [300, 280], [450, 400]],   # Day 1
                            [[130, 140], [320, 300], [460, 420]],   # Day 2
                            [[125, 135], [310, 290], [455, 410]]])  # Day 3

print("Traffic Data Over Three Days at Two Intersections:")
print(traffic_data_3d)

Traffic Data Over Three Days at Two Intersections:
[[[120 130]
  [300 280]
  [450 400]]

 [[130 140]
  [320 300]
  [460 420]]

 [[125 135]
  [310 290]
  [455 410]]]



### 2.3 Analyzing Environmental Data (1.3 Extension)

Let’s consider another example where we create an array to represent temperature data collected from three different monitoring stations around Kathmandu over a week. This data can help in analyzing micro-climate variations across the city.

#### Example: Temperature Data from Multiple Stations

In [10]:
# Temperature data from three stations in Kathmandu over a week (each row represents a day)
temperature_data = np.array([[15.5, 16.1, 15.8],
                             [16.8, 17.3, 16.9],
                             [18.1, 18.6, 18.0],
                             [17.3, 17.8, 17.4],
                             [19.2, 19.7, 19.1],
                             [20.5, 21.0, 20.6],
                             [21.2, 21.7, 21.3]])

# Days of the week
days_of_week = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]

# Print table header
print(f"+{'-'*12}+{'-'*18}+{'-'*18}+{'-'*18}+")
print(f"| {'Day':<10} | {'Station 1 (°C)':<16} | {'Station 2 (°C)':<16} | {'Station 3 (°C)':<16} |")
print(f"+{'-'*12}+{'-'*18}+{'-'*18}+{'-'*18}+")

# Print table rows
for day, temps in zip(days_of_week, temperature_data):
    print(f"| {day:<10} | {temps[0]:<16} | {temps[1]:<16} | {temps[2]:<16} |")

# Print table footer
print(f"+{'-'*12}+{'-'*18}+{'-'*18}+{'-'*18}+")

+------------+------------------+------------------+------------------+
| Day        | Station 1 (°C)   | Station 2 (°C)   | Station 3 (°C)   |
+------------+------------------+------------------+------------------+
| Sunday     | 15.5             | 16.1             | 15.8             |
| Monday     | 16.8             | 17.3             | 16.9             |
| Tuesday    | 18.1             | 18.6             | 18.0             |
| Wednesday  | 17.3             | 17.8             | 17.4             |
| Thursday   | 19.2             | 19.7             | 19.1             |
| Friday     | 20.5             | 21.0             | 20.6             |
| Saturday   | 21.2             | 21.7             | 21.3             |
+------------+------------------+------------------+------------------+



## 3. Array Operations

Numpy allows you to perform a variety of operations on arrays, such as element-wise arithmetic, statistical analysis, and even more complex operations like broadcasting. These operations are highly optimized and are significantly faster than performing similar tasks with Python lists.

### 3.1 Element-wise Operations
Element-wise operations in Numpy involve performing operations (like addition, subtraction, multiplication, etc.) on each element of the array. This is particularly useful when you’re working with datasets like temperatures, pollution levels, or traffic counts, where you might want to apply the same operation to all data points.

In [11]:
# Element-wise addition
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
result_add = array_a + array_b
print("Element-wise Addition:", result_add)

# Element-wise multiplication
result_mult = array_a * array_b
print("Element-wise Multiplication:", result_mult)


Element-wise Addition: [5 7 9]
Element-wise Multiplication: [ 4 10 18]


### Example: Calculating Daily Temperature Differences
Suppose we want to calculate the temperature difference between consecutive days in Kathmandu. This can help in analyzing how much the temperature fluctuates from day to day.

In [12]:
# Temperature data from Kathmandu over a week
temp_data = np.array([15.5, 16.8, 18.1, 17.3, 19.2, 20.5, 21.2])

# Calculate the difference between consecutive days
temp_diff = np.diff(temp_data)
print("Temperature Difference Between Consecutive Days:", temp_diff)

Temperature Difference Between Consecutive Days: [ 1.3  1.3 -0.8  1.9  1.3  0.7]


#### In this example:
- The np.diff function calculates the difference between each pair of consecutive elements in the temp_data array.
- The result is an array showing the temperature change from one day to the next.


### 3.2 Broadcasting in Numpy

Numpy supports broadcasting, allowing you to perform operations on arrays of different shapes. Broadcasting is one of the most powerful features of Numpy. It allows you to perform operations on arrays of different shapes as if they were the same shape. This is done by automatically expanding the smaller array along the “missing” dimensions.


In [13]:
# Broadcasting example
array_c = np.array([1, 2, 3])
array_d = np.array([[4], [5], [6]])
result_broadcast = array_c + array_d
print("Broadcasting Result:\n", result_broadcast)

Broadcasting Result:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


### Example: Applying a Temperature Correction Factor
Let’s assume that all temperature measurements need a correction factor of -0.5 degrees due to calibration errors. We can apply this correction across the entire dataset using broadcasting.

In [14]:
# Apply a correction factor of -1.32 to all temperature data
corrected_temp_data = temp_data - 1.32
print("Corrected Temperature Data:", corrected_temp_data)

Corrected Temperature Data: [14.18 15.48 16.78 15.98 17.88 19.18 19.88]


### 3.3 Statistical Operations

Numpy provides a range of statistical functions to help you analyze your data. These include functions to calculate the mean, median, standard deviation, and more. Let’s use these functions to analyze the temperature data from Kathmandu.

#### Example: Analyzing Temperature Data with Statistics

In [15]:
# Calculate basic statistics
mean_temp = np.mean(temp_data)
max_temp = np.max(temp_data)
min_temp = np.min(temp_data)
std_dev_temp = np.std(temp_data)

print(f"Mean Temperature: {mean_temp:.2f}°C")
print(f"Maximum Temperature: {max_temp}°C")
print(f"Minimum Temperature: {min_temp}°C")
print(f"Standard Deviation of Temperature: {std_dev_temp:.2f}°C")

Mean Temperature: 18.37°C
Maximum Temperature: 21.2°C
Minimum Temperature: 15.5°C
Standard Deviation of Temperature: 1.90°C


#### In this example:

- np.mean(temp_data) calculates the average temperature over the week.
- np.max(temp_data) finds the highest temperature recorded during the week.
- np.min(temp_data) finds the lowest temperature recorded during the week.
- np.std(temp_data) calculates the standard deviation, which indicates how much the temperatures vary from the mean.

These statistical operations are essential for summarizing and understanding your data, especially when dealing with large datasets.



## 4. Indexing and Slicing

Indexing and slicing are fundamental operations in Numpy that allow you to access and modify specific parts of your array. These operations are similar to those used with Python lists, but Numpy extends them to multi-dimensional arrays.

In the context of data analysis in Kathmandu, indexing and slicing can be extremely useful. For instance, you might want to focus on traffic data from a particular time of day or a specific intersection. Let’s explore how this works with some examples.

### 4.1 Accessing Elements
We can access individual elements of a Numpy array using indexing. For a 2D array, you provide the row index and the column index to access a specific element.

#### Example: Accessing Traffic Data for Noon at Intersection 1

Let’s say we want to access the traffic data for the noon time period at Intersection 1.

In [16]:
# Traffic data at two intersections (intersection 1, intersection 2) across three time periods (morning, noon, evening)
traffic_data = np.array([[3200, 6300], [4000, 8800], [4500, 6400]])

# Accessing the traffic data for Noon at Intersection 1
noon_intersection1 = traffic_data[1, 0]
print("Traffic Data for Noon at Intersection 1:", noon_intersection1)

Traffic Data for Noon at Intersection 1: 4000


Here, ```traffic_data[1, 0]``` accesses the element in the second row (Noon) and the first column (Intersection 1), giving us the traffic count at that specific time and location.



### 4.2 Slicing Arrays

Slicing allows you to extract a subset of the array. This is particularly useful when you want to analyze a specific time period across all intersections, or vice versa.

#### Example: Extracting Traffic Data for All Intersections at Noon

Let’s extract the traffic data for the noon time period across both intersections.

In [17]:
# Extracting the traffic data for all intersections at Noon
noon_traffic = traffic_data[1, :]
print("Traffic Data for All Intersections at Noon:", noon_traffic)

Traffic Data for All Intersections at Noon: [4000 8800]


In this example, ```traffic_data[1, :]``` selects the entire row corresponding to the noon time period, giving us the traffic counts for both intersections at that time.


### 4.3 Advanced Slicing: Extracting Morning and Evening Traffic Data

You can also extract multiple rows or columns at once using slicing. For instance, if you want to analyze the traffic data for the morning and evening periods (but not noon), you can do so with slicing.

#### Example: Extracting Morning and Evening Traffic Data

In [18]:
# Extracting the traffic data for Morning and Evening across both intersections
morning_evening_traffic = traffic_data[[0, 2], :]
print("Traffic Data for Morning and Evening at Both Intersections:")
print(morning_evening_traffic)

Traffic Data for Morning and Evening at Both Intersections:
[[3200 6300]
 [4500 6400]]


In this case, ```traffic_data[[0, 2], :]``` selects the first and third rows (Morning and Evening) for all columns (both intersections).


#### Displaying Sliced Data in a Table

Finally, let’s display the extracted data in a table format to make it more readable.

#### Example: Displaying Morning and Evening Traffic Data

In [19]:
# Time periods for the sliced data
time_periods_sliced = ["Morning", "Evening"]

# Print table header
print(f"+{'-'*12}+{'-'*18}+{'-'*18}+")
print(f"| {'Time ':<10} | {'Intersection 1':<16} | {'Intersection 2':<16} |")
print(f"+{'-'*12}+{'-'*18}+{'-'*18}+")

# Print table rows
for time, traffic in zip(time_periods_sliced, morning_evening_traffic):
    print(f"| {time:<10} | {traffic[0]:<16} | {traffic[1]:<16} |")

# Print table footer
print(f"+{'-'*12}+{'-'*18}+{'-'*18}+")

+------------+------------------+------------------+
| Time       | Intersection 1   | Intersection 2   |
+------------+------------------+------------------+
| Morning    | 3200             | 6300             |
| Evening    | 4500             | 6400             |
+------------+------------------+------------------+



## 5. Array Manipulation

Array manipulation is one of the key features of Numpy that makes it so powerful for data processing tasks. Numpy provides various functions to reshape, join, split, and otherwise modify arrays, allowing you to organize your data in the most convenient format for analysis.
### 5.1 Reshaping Arrays
Reshaping arrays means changing their shape without altering the data. This is particularly useful when you want to compare or analyze data in different configurations.



In [20]:
print(array_1d)
# Reshaping a 1D array to a 2D array
reshaped_array = array_1d.reshape(1, 5)
print("Reshaped Array:\n", reshaped_array)


[1 2 3 4 5]
Reshaped Array:
 [[1 2 3 4 5]]



#### Example: Reshaping Traffic Data for Comparison

Let’s say we have traffic data for three different times of the day (morning, noon, evening) at two intersections in Kathmandu. Suppose we want to reshape this data to compare traffic volumes across the intersections for each time period.

In [21]:
# Traffic data at two intersections across three time periods (morning, noon, evening)
traffic_data = np.array([[3200, 6300], [4000, 8800], [4500, 6400]])
print(traffic_data)
# Reshape the traffic data for comparison
reshaped_traffic_data = traffic_data.reshape(2, 3)
print("Reshaped Traffic Data for Comparison:")
print(reshaped_traffic_data)

[[3200 6300]
 [4000 8800]
 [4500 6400]]
Reshaped Traffic Data for Comparison:
[[3200 6300 4000]
 [8800 4500 6400]]


In this example:

- The reshape(2, 3) method changes the shape of the array from a 3x2 matrix (3 time periods, 2 intersections) to a 2x3 matrix, allowing for easier comparison of traffic volumes across different intersections.

### 5.2 Joining Arrays
Joining arrays involves combining multiple arrays into one. This is useful when you have data from multiple sources that you want to analyze together.


In [22]:
# Joining two arrays
joined_array = np.concatenate((array_a, array_b))
print("Joined Array:", joined_array)

# Splitting an array
split_array = np.array_split(joined_array, 3)
print("Split Arrays:", split_array)


Joined Array: [1 2 3 4 5 6]
Split Arrays: [array([1, 2]), array([3, 4]), array([5, 6])]


#### Example: Combining Traffic Data from Two Different Days

Suppose we have traffic data from two different days and we want to combine this data into a single array for analysis.

In [23]:
# Traffic data for Day 1
day1_traffic = np.array([[3200, 6300], [4000, 8800], [4500, 6400]])

# Traffic data for Day 2
day2_traffic = np.array([[3300, 6400], [4100, 8900], [4600, 6500]])

# Combine the traffic data from both days
combined_traffic_data = np.concatenate((day1_traffic, day2_traffic), axis=0)
print("Combined Traffic Data from Two Days:")
print(combined_traffic_data)

Combined Traffic Data from Two Days:
[[3200 6300]
 [4000 8800]
 [4500 6400]
 [3300 6400]
 [4100 8900]
 [4600 6500]]


In this example:

- The np.concatenate function joins the two arrays along the specified axis. Here, axis=0 means the arrays are stacked vertically, resulting in a single array that contains traffic data from both days.

### 5.3 Splitting Arrays

Splitting arrays allows you to divide a larger array into smaller sub-arrays. This can be useful for segmenting data into more manageable parts or analyzing specific portions of the dataset.

#### Example: Splitting Traffic Data by Time Period

Suppose you want to split the traffic data into separate arrays for each time period to analyze them individually.

In [24]:
# Split the traffic data by time period
morning_traffic, noon_traffic, evening_traffic = np.array_split(traffic_data, 3)
print("Morning Traffic Data:")
print(morning_traffic)
print("Noon Traffic Data:")
print(noon_traffic)
print("Evening Traffic Data:")
print(evening_traffic)

Morning Traffic Data:
[[3200 6300]]
Noon Traffic Data:
[[4000 8800]]
Evening Traffic Data:
[[4500 6400]]


In this example:

- The np.array_split function divides the traffic_data array into three sub-arrays, each corresponding to a different time period (morning, noon, evening).

### 5.4 Displaying Reshaped Data in a Table

Finally, let’s display the reshaped traffic data in a table format to make it easier to understand and compare.

#### Example: Displaying Reshaped Traffic Data

In [25]:
# Intersections and time periods for the reshaped data
intersections = ["Intersection 1", "Intersection 2"]
time_periods_reshaped = ["Morning", "Noon", "Evening"]

# Print table header
print(f"+{'-'*18}+{'-'*12}+{'-'*12}+{'-'*12}+")
print(f"| {'Intersection':<16} | {time_periods_reshaped[0]:<10} | {time_periods_reshaped[1]:<10} | {time_periods_reshaped[2]:<10} |")
print(f"+{'-'*18}+{'-'*12}+{'-'*12}+{'-'*12}+")

# Print table rows
for i, traffic in enumerate(reshaped_traffic_data):
    print(f"| {intersections[i]:<16} | {traffic[0]:<10} | {traffic[1]:<10} | {traffic[2]:<10} |")

# Print table footer
print(f"+{'-'*18}+{'-'*12}+{'-'*12}+{'-'*12}+")

+------------------+------------+------------+------------+
| Intersection     | Morning    | Noon       | Evening    |
+------------------+------------+------------+------------+
| Intersection 1   | 3200       | 6300       | 4000       |
| Intersection 2   | 8800       | 4500       | 6400       |
+------------------+------------+------------+------------+


## Numpy Basic { Summary Table }

| **Section**             | **Key Points**                                                                                                                                                      |
|-------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **1. Introduction to Numpy**  | - Numpy is essential for efficient numerical computations and data processing.                                                                                |
|                         | - Supports multi-dimensional arrays (1D, 2D, 3D, etc.).                                                                                                           |
|                         | - Provides a vast library of mathematical functions.                                                                                                              |
|                         | - Commonly used in scientific computing, data analysis, and machine learning.                                                                                     |
|                         | - Example: Analyzing temperature data in Kathmandu over a week.                                                                                                    |
| **2. Creating Numpy Arrays**  | - Arrays can be created from lists, representing data like temperature, traffic, etc.                                                                         |
|                         | - 1D Arrays: Represent simple data like vehicle counts at different times.                                                                                        |
|                         | - 2D Arrays: Handle more complex data structures like traffic counts at multiple intersections.                                                                   |
|                         | - 3D Arrays: Used for even more complex datasets, like traffic data over multiple days.                                                                            |
|                         | - Example: Creating and manipulating arrays to represent traffic data in Kathmandu.                                                                                |
| **3. Array Operations**       | - **Element-wise Operations**: Perform operations on each element of the array, e.g., calculating temperature differences.                                    |
|                         | - **Broadcasting**: Apply operations to arrays of different shapes, e.g., applying a temperature correction factor across all data points.                        |
|                         | - **Statistical Operations**: Analyze data with functions like mean, max, min, and standard deviation.                                                            |
|                         | - Example: Performing operations to analyze and modify temperature data in Kathmandu.                                                                              |
| **4. Indexing and Slicing**   | - **Indexing**: Access specific elements of an array, e.g., traffic data for a specific time and intersection.                                               |
|                         | - **Slicing**: Extract sub-arrays for analysis, e.g., traffic data for all intersections at noon.                                                                 |
|                         | - **Advanced Slicing**: Extract multiple rows/columns at once, e.g., morning and evening traffic data.                                                            |
|                         | - Example: Accessing and slicing traffic data to focus on specific periods or intersections.                                                                       |
| **5. Array Manipulation**     | - **Reshaping Arrays**: Change the shape of an array for comparison, e.g., comparing traffic volumes across intersections.                                   |
|                         | - **Joining Arrays**: Combine multiple arrays into one, e.g., combining traffic data from different days.                                                         |
|                         | - **Splitting Arrays**: Divide an array into smaller sub-arrays, e.g., splitting traffic data by time period.                                                     |
|                         | - Example: Manipulating arrays to organize and analyze traffic data in different configurations.                                                                  |